---
- hosts: local
  gather_facts: no
  connection: local

  tasks:
  - name: install casks
    homebrew_cask: name={{item}} state=present
    with_items:
    - hipchat
    - iterm2
    - alfred
    - vagrant
    - google-chrome
    - dropbox
    - vagrant
    - slack
    - spotify
    - pritunl 
    - keepassxc
    #- istat-menus
    - crashplan
    - teamviewer
    - winbox
    - steam
    - handbrake
    - vlc
    - transmit
    - transmission
    - atom
    - simplenote
    - hex-fiend
  - name: install brews
    homebrew: name={{item}} state=present
    with_items:
    - ruby
    - mercurial
    - wget
    - tmux
    - sshuttle
    #- glances
    - swaks
    - mobile-shell
    - youtube-dl
    - git
    - vim
  #- name: install xcode
  #  sudo: true
  #  command: xcode-select --install
  - name: install PIP stuff
    pip: name={{item}} state=present

    with_items:
    - virtualenvwrapper
    - fabric
    - boto
    - boto3
    - awscli
    - ipython
    - ipdb

  - name: download dotfiles
    git: repo=https://github.com/jerm/dotfiles dest=~/.dotfiles

  - name: install dotfiles
    shell: bash -c "cd ~/.dotfiles; ./setup.rb"

  #- name: install mac apps package
  #  command: curl -s http://getmacapps.com/raw/3oitluxdna4l | sh


