---
- hosts: local
  gather_facts: no
  connection: local

  tasks:
  - name: install homebrew taps
    homebrew_tap:
      name: {{ item }}
    with_items:
    - wallix/awless

  - name: install brews
    homebrew: name={{item}} state=present
    with_items:
    - ruby
    - mercurial
    - wget
    - tmux
    - sshuttle
    - npm
    - node
    - readline
    - nmap
    - go
    #- glances
    - swaks
    - mobile-shell
    - youtube-dl
    - git
    - vim
    - terraform
    - jq
    - yq
    - cli53
    - autojump
    - ripgrep
    - gron
    - autoenv
    - ponysay
    - htop
    - gpg
    - awless
    - pipenv
    - mypy
    - httpie
    - hub


  - name: install casks
    homebrew_cask: name={{item}} state=present
    ignore_errors: true
    with_items:
    - hipchat
    - iterm2
    - alfred
    - vagrant
    - google-chrome
    - dropbox
    - slack
    - spotify
    - pritunl
    - keepassxc
    - teamviewer
    - winbox
    - steam
    - handbrake
    - vlc
    - transmit
    - transmission
    - atom
    - simplenote
    - hex-fiend
    - sonos
    - ngrok
    - istat-menus
    tags: casks

  - name: install sudo casks
    homebrew_cask: name={{item}} state=present
    # become: true
    # become_user: root
    ignore_errors: true
    with_items:
    - keybase
    tags: sudo_casks
  #- name: install xcode
  #  sudo: true
  #  command: xcode-select --install

  - name: install PIP stuff
    pip: name={{item}} state=present

    with_items:
    - virtualenvwrapper
    - fabric
    - boto
    - boto3
    - awscli
    - ipython
    - ipdb
    - speedtest-cli
    - awsebcli

  - name: download dotfiles
    git: repo=https://github.com/jerm/dotfiles dest=~/.dotfiles

  - name: install dotfiles
    shell: bash -c "cd ~/.dotfiles; ./setup.rb"



  #- name: install mac apps package
  #  command: curl -s http://getmacapps.com/raw/3oitluxdna4l | sh


